plugins {
    id 'com.android.application'
}

android {
    namespace 'com.zing.video_crawler'
    compileSdk 34

    defaultConfig {
        applicationId 'com.zing.video_crawler'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0'

        externalNativeBuild {
            cmake {
                cppFlags ''
            }
        }
        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            jniDebuggable true
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    buildFeatures {
        buildConfig true
        viewBinding true
    }

    // 启用 .so 压缩，降低 APK 体积（Android 7+ 影响较小）
    packagingOptions {
        jniLibs {
            useLegacyPackaging = false
        }
    }

    // 输出多架构 APK，可选
    splits {
        abi {
            enable true
            reset()
            include 'arm64-v8a', 'armeabi-v7a', 'x86', 'x86_64'
            universalApk true
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
